### ISSUE TITLE
Some configurations are missing

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-gastronomies#8]
According to the Briefing sent some configurations of the web component on the web component store are missing.

In particular actually for a web component store user are missing the following configuration opportunity:
- [x] set a radius for the query;
- [x] select the types of gastronomies (e.g. pizzeria, restaurant, mountain refuge, alpine hut, etc.) to be shown;
- [x] activate/deactivate the “get directions” button. The button could redirect the user to google maps for the navigation.

@GnuRant

**Comment by lcfd** [comment]
Hi, @sseppi point 1 and 3 are in PR. 
Point 2 is still on hold due to filter level decisions.

@Piiit @GnuRant

**Comment by Piiit** [comment]
@lcfd @GnuRant
We decided to always take the categories from the API, and always do the call and not hardcode them inside JS. Gastronomie types should be configurable, that means give a list which should be shown (whitelisting). Or show all if not list has been given.

**Comment by lcfd** [comment]
@RudiThoeni 

I have a filter that is facilityCodesCreditCard that has those possible values:

```
0: (2) ["Carta di credito", 1]
1: (2) ["Bankomat/Maestro", 2]
```
But on the ​`/api​/GastronomyReduced` endpoint I can't see a parameter to use those `FacilityCodes_CreditCard`

**Comment by RudiThoeni** [comment]
Hi Luca

Sorry the swagger text ist a little bit outdated
http://tourism.opendatahub.bz.it/api/GastronomyTypes

switch(Type) ;)))

all which begins with FacilityCodes_ --> facilitycodefilter  where you pass the bitmask
all CuisineCodes --> cuisinecodefilter 
all CeremonyCodes --> ceremonycodefilter
all DishCodes --> dishcodefilter
all CategoryCodes --> categorycodefilter
